collections:
#  - name: community.general
#  - name: community.crypto
#  - name: community.vmware
#  - name: azure.azcollection
  - name: https://github.com/zaskan/sample_namespace.sample_collection.git
    type: git
    version: main
