- name: reload firewalld
  service:
    name: firewalld
    state: reloaded

- name: restart iptables
  service:
    name: iptables
    state: restarted
  when:
    - ansible_facts.services['iptables.service'] | default([]) | length
    - ansible_facts.services['iptables.service'].status == 'enabled'

