---
- name: Create configuration directory for Pulp
  file:
    path: '{{ pulp_config_dir }}'
    state: directory
    owner: root
    group: '{{ pulp_group }}'
    mode: 0750
    serole: _default
    setype: _default
    seuser: _default

- name: Create configuration file for Pulp
  template:
    src: settings.py.j2
    dest: '{{ pulp_settings_file }}'
    owner: root
    group: '{{ pulp_group }}'
    mode: 0640
    force: yes
    serole: _default
    setype: _default
    seuser: _default
  notify: Restart all Pulp services

- name: Create local configuration file for Pulp
  ansible.builtin.file:
    path: '{{ pulp_settings_file_local }}'
    state: touch
    modification_time: preserve
    access_time: preserve
    mode: 0640
    owner: root
    group: '{{ pulp_group }}'
    serole: _default
    setype: _default
    seuser: _default

- name: Create wrapper to call pulpcore-manager
  template:
    src: pulpcore-manager.j2
    dest: "/usr/local/bin/pulpcore-manager"
    owner: root
    group: "{{ pulp_group }}"
    mode: "0750"

- name: Configure sudo for pulpcore-manager
  lineinfile:
    path: /etc/sudoers.d/pulpcore-manager
    line: "%{{ pulp_group }} ALL=({{ pulp_user }}:{{ pulp_group }}) NOPASSWD:SETENV: {{ pulp_django_admin_path }}"
    create: true
    owner: root
    group: root
    mode: "0440"
    serole: _default
    setype: _default
    seuser: _default

- name: Set up galaxy-importer config
  include_tasks: galaxy_importer.yml
  when: galaxy_importer_settings is defined

- name: Set up API access log
  include_tasks: setup_galaxy_api_access_log.yml

- name: Set up collection signing
  include_tasks: collection_signing_service.yml
  when: automationhub_create_default_collection_signing_service | bool

- name: Set up container signing
  include_tasks: container_signing_service.yml
  when: automationhub_create_default_container_signing_service | bool
