---
- name: Create credential in Ansible Automation Platform
  hosts: localhost
  gather_facts: false
  collections:
    - ansible.controller

  tasks:
  - name: Create credential
    ansible.controller.credential:
      name: Credential for Organization 1
      description: Credential for Organization 1
      organization: Organization2
      credential_type: Machine
      state: present
      inputs:
        username: cloud-user
        password: password
      validate_certs: false
    register: result

  - name: Show result
    debug:
      var: result