---
- name: Create credential in Ansible Automation Platform
  hosts: localhost
  gather_facts: false
  collections:
    - ansible.controller

  tasks:
  - name: Create credential
    ansible.controller.credential:
      name: "Credential for Organization 1"
      description: "Credential for Organization 1"
      organization: "Organization2"
      credential_type: "Machine"
      state: exists
      inputs:
        username: "cloud-user"
        password: "password"
      validate_certs: false
    register: result

  - name: Add to Job Template
    ansible.controller.job_template:
      name: "MY Job Template Organization1"
      inventory: "Inventory Organization1"
      job_type: "run"
      organization: "Organization1"
      playbook: "hello_world.yml"
      project: "Project Organization1"
      credential: "Credential for Organization 1"
      validate_certs: false