---
- name: Create credential in Ansible Automation Platform
  hosts: localhost
  gather_facts: false
  collections:
    - ansible.controller

   tasks:
    - name: Create credential
      ansible.controller.credential:
        name: Credential for Organization 1
        description: Credential for Organization 1
        organization: Organization2
        credential_type: Machine
        state: present
        inputs:
          username: "{{ lookup('community.general.bitwarden_secrets_manager', '6404c3c6-b46d-4e9d-8429-b32c00650238').value }}"
          password: "{{ lookup('community.general.bitwarden_secrets_manager', '2791e7c4-96a5-4a26-bc45-b32c00650ed8').value }}"
          ssh_key_data: "{{ lookup('community.general.bitwarden_secrets_manager', '16e67ff6-d7c6-47b1-9adc-b32c00615c85').value }}"
        validate_certs: false
      register: result

    - name: Show result
      debug:
        var: result