---
- name: Create credential in Ansible Automation Platform
  hosts: localhost
  gather_facts: false
  collections:
    - ansible.controller

  tasks:
  - name: Create credential
    ansible.controller.credential:
      name: "Credential for Organization 1"
      state: absent
      validate_certs: false
    register: result

  - name: Update Job Template
    ansible.controller.job_template:
      name: "MY Job Template Organization1"
      inventory: "Inventory Organization1"
      job_type: "run"
      organization: "Organization1"
      playbook: "hello_world.yml"
      project: "Project Organization1"
      validate_certs: false
