---
- name: Test local facts
  gather_facts: false
  hosts: all
  tasks:
    - name: Show facts
      ansible.builtin.debug:
        msg:  "{{ ansible_facts.ansible_date_time.date }} {{ ansible_facts.ansible_date_time.time }} {{ ansible_facts.ansible_date_time.tz }}"
