- name: Play 2 - Retrieve and Use Stats
  hosts: localhost
  gather_facts: no  # No need to gather facts again
  tasks:

    - name: Show the normal variable (if overridden by -e)
      debug:
        msg: "my_var is {{ stat1 }}"
