---
- name: test
  gather_facts: true
  hosts: all
  tasks:
    - ansible.builtin.setup:
        fact_path: /etc/ansible/facts.d

    - debug: msg="{{ ansible_local['preferences']['general']['machine_type'] }}"
