---
- name: Assert Receptor Network Mesh data
  include_tasks: preflight.yml
  when: mesh is not defined

- name: Install receptor
  dnf:
    name: "{{ receptor_dependencies_list }}"
    state: latest
  notify:
    - "Restart Receptor"

- name: Install receptor dependencies
  dnf:
    name: "{{ receptor_workable_dependencies }}"
    state: latest
  when:
    - receptor_workable_dependencies is defined
    - node_type in receptor_workable_types

- name: Install ansible-runner for execution plane
  dnf:
    name: ansible-runner
    state: latest
  when:
    - node_type == "execution"

- name: Update existing dependent packages
  include_role:
    name: ansible.automation_platform_installer.repo_management
    tasks_from: update_dependency

- name: Invoke Receptor TLS
  when: receptor_tls | bool
  block:

    - name: Reconfigure Receptor CA (forced)
      file:
        dest: "{{ receptor_tls_dir }}"
        state: absent
      when: (receptor_tls_reconfigure | bool) or
            (mesh_ca_certfile | default('') | length) or
            (mesh_ca_keyfile | default('') | length)

    - name: Create Receptor CA directory
      file:
        dest: "{{ receptor_tls_ca_dir }}"
        state: directory
        mode: '0750'
        owner: receptor
        group: receptor
        recurse: yes

    - name: Configure Receptor Certificate Authority
      include_tasks: tls_ca.yml
      run_once: true
      when:
        - groups['automationcontroller'] | default([]) | length
        - inventory_hostname == groups['automationcontroller'][0]

    - name: Generate Receptor Mesh Nodes certificates
      include_tasks: tls_nodes.yml

    - name: Sign Receptor Mesh Node Certificates
      include_tasks: tls_ca_sign.yml

- name: Create awx group
  group:
    name: "{{ run_receptor_as }}"

- name: Adds awx user to receptor group
  user:
    name: "{{ run_receptor_as }}"
    group: "{{ run_receptor_as }}"
    groups: receptor
    append: yes
    home: /var/lib/awx
    shell: /bin/bash

- name: Configure the user's home directory
  file:
    path: /var/lib/awx
    state: directory
    owner: "{{ run_receptor_as }}"
    group: "{{ run_receptor_as }}"
    mode: '0755'

- name: Include datadir asserts
  include_tasks: assert_datadir.yml
  when:
    - receptor_datadir is defined
    - receptor_datadir != ''

- name: Ensure soft/hard file descriptors limits
  template:
    src: templates/pam_limits_awx.conf.j2
    dest: /etc/security/limits.d/awx.conf
    mode: '0600'
    owner: root
    group: root

- name: Create and and distribute keys for signing work
  import_tasks: work_sign_keys.yml

- name: Allow awx user to read receptor configuration
  file:
    dest: /etc/receptor
    state: directory
    owner: receptor
    group: awx
    mode: "0750"

- name: Ensure systemd override directory exists
  file:
    dest: /etc/systemd/system/receptor.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Override receptor's systemd service runuser
  template:
    src: templates/systemd_receptor_override.conf.j2
    dest: /etc/systemd/system/receptor.service.d/override.conf
    mode: '0644'
    owner: root
    group: root
  notify: Restart Receptor

- name: Configure the awx-receptor socket directory.
  file:
    path: "{{ receptor_socket_dir }}"
    state: directory
    owner: "{{ run_receptor_as }}"
    group: "{{ run_receptor_as }}"
    mode: '0750'

- name: Create tmpfiles.d entry for awx-receptor socket directory
  template:
    src: templates/awx-receptor_tmpd.conf
    dest: /etc/tmpfiles.d/awx-receptor.conf
    force: yes
    mode: '0640'
    owner: root
    group: root

- name: Create tmpfiles.d entry for receptor socket directory
  template:
    src: templates/receptor_tmpd.conf
    dest: /etc/tmpfiles.d/receptor.conf
    force: yes
    mode: '0640'
    owner: root
    group: root

- name: Configure firewall
  include_role:
    name: ansible.automation_platform_installer.firewall
  vars:
    firewalld_http_port: "{{ _nginx_http_port | default(80) }}"
    firewalld_https_port: "{{ _nginx_https_port | default(443) }}"

- name: Configure podman
  include_role:
    name: ansible.automation_platform_installer.podman
  vars:
    run_podman_as: "{{ run_receptor_as }}"
  when: node_type in receptor_workable_types

- set_fact:
    _fips_enabled: "{{ ansible_fips }}"

- name: Disable minTLS13 if any node is FIPS enabled
  set_fact:
    _disable_mintls13: "{{ (hostvars | dict2items | selectattr('value._fips_enabled', 'defined') | selectattr('value._fips_enabled') | length) | ternary(true, false) }}"
  run_once: true

- name: Deploy receptor config
  template:
    src: templates/receptor.conf.j2
    dest: /etc/receptor/receptor.conf
    mode: '0644'
    owner: receptor
    group: receptor
  notify:
    - "Receptor Reload Type"

- name: Start Receptor service
  systemd:
    name: receptor
    state: started
    daemon_reload: yes
    enabled: yes

- name: Register instances and queues and check mesh connectivity
  include_tasks: register_instances.yml
