---
- name: start PostgreSQL
  service:
    name: '{{ postgres_init_name }}'
    state: started
  when: config_dynamic_database == 'internal'

- name: restart supervisor
  service:
    name: supervisord
    state: restarted