- name: 'Add resource'
  uri:
    url: '{{ sso_api_client_url }}/authz/resource-server/resource'
    body: '{{ resource | to_json }}'
    body_format: json
    headers:
      Accept: application/json
      Authorization: 'Bearer {{ sso_token }}'
      Content-type: application/json
    method: POST
    validate_certs: no
    status_code:
      - 201
      - 409
