---
pulp_preq_packages:
  - '{{ pulp_pkg_name_prefix }}devel'
  - python3-libselinux  # For ansible itself
  - gcc                 # For psycopg2
  - make                # For make docs, and SELinux policy install
  - libpq-devel         # Renamed/Split version of postgresql-devel
  - git                 # For source install, and SELinux policy install
  - sudo
  - gnupg2              # For the signing service via the gpg python module
  - openldap-devel
  - tar
pulp_install_object_storage: filesystem
pulp_pip_editable: yes
pulp_use_system_wide_pkgs: false
pulpcore_update: false
prereq_pip_packages:
  - Jinja2
  - pygments
  - setproctitle
# The order is significant; linear order to handle the dependency tree
__pulp_selinux_policy_pkgs:
  - pulpcore_port
  - pulpcore
  - pulpcore_rhsmcertd
__pulp_selinux_repo: 'https://github.com/pulp/pulpcore-selinux.git'
__pulp_selinux_version: '1.3.2'
__pulp_binaries:
  - "{{ pulp_install_dir }}/bin/gunicorn"
  - "{{ pulp_install_dir }}/bin/pulpcore-worker"
