---
# tasks file for pulp_api

- name: Ensure python-cryptography is installed
  package:
    name: '{{ pulp_python_cryptography }}'

- import_tasks: generate_token_auth_key.yml
  when: pulp_token_auth_key is undefined

- import_tasks: import_token_auth_key.yml
  when: pulp_token_auth_key is defined

- name: Extract token authentication public key
  openssl_publickey:
    path: "{{ pulp_certs_dir }}/token_public_key.pem"
    privatekey_path: "{{ pulp_certs_dir }}/token_private_key.pem"
    mode: 0644
    owner: "{{ pulp_user }}"
    group: "{{ pulp_group }}"
    serole: _default
    setype: _default
    seuser: _default
    backup: true
  become: true
  become_user: "{{ pulp_user }}"

- name: Install pulpcore-api service files
  template:
    src: pulpcore-api.service.j2
    dest: /lib/systemd/system/pulpcore-api.service
    owner: root
    group: root
    mode: 0644
  notify: Restart pulpcore-api.service

- name: Set the pulpcore-api service state
  systemd:
    name: pulpcore-api.service
    state: started
    enabled: true
    daemon_reload: true
