---
- name: Check for SECRET_KEY
  stat:
    path: "/etc/ansible-automation-platform/eda/SECRET_KEY"
  register: automationedacontroller_secret_key_path

- name: Set SECRET_KEY
  template:
    src: SECRET_KEY.j2
    dest: "/etc/ansible-automation-platform/eda/SECRET_KEY"
    owner: eda
    group: root
    mode: "0600"
  no_log: "{{ _no_log }}"
  notify: restart automation-eda-controller
  when: not automationedacontroller_secret_key_path.stat.exists

- name: Get SECRET_KEY
  slurp:
    src: "/etc/ansible-automation-platform/eda/SECRET_KEY"
  register: automationedacontroller_secret_key_slurp
  no_log: "{{ _no_log }}"