---
# Create and manage the pulp user account
- name: Make sure {{ pulp_group }} group exists
  group:
    name: '{{ pulp_group }}'
    gid: '{{ pulp_group_id }}'
    state: present
    system: true

- name: Create user {{ pulp_user }}
  user:
    name: '{{ pulp_user }}'
    uid: '{{ pulp_user_id }}'
    shell: '/usr/sbin/nologin'
    home: '{{ pulp_user_home }}'
    system: true
    group: '{{ pulp_group }}'
    groups:
      - '{{ pulp_group }}'
    append: true
  notify: Restore SELinux contexts on Pulp dirs that must exist

- name: Check if the redis group exists
  command: getent group redis
  changed_when: False
  check_mode: False
  register: redis_group
  failed_when: redis_group.rc not in [0, 2]

- name: Add user pulp to the redis group
  user:
    name: '{{ pulp_user }}'
    groups: redis
    append: true
  when: redis_group.rc == 0

- name: Reset ssh conn to allow user changes to affect when ssh user and pulp user are the same
  meta: reset_connection
