---
- name: Ensure sso_api_url_base is set
  fail:
    msg: "sso_api_url_base must be set"
  when: not sso_api_url_base | default('') | length

- name: Ensure sso_console_admin_username and sso_console_admin_password are set
  fail:
    msg: "sso_console_admin_username and sso_console_admin_password must be set"
  when: not sso_console_admin_username | default('') | length or not sso_console_admin_password | default('') | length

- name: Create SSO token
  uri:
    url: "{{ sso_api_url_base }}/realms/master/protocol/openid-connect/token"
    method: POST
    body_format: form-urlencoded
    body:
      grant_type: "password"
      client_id: 'admin-cli'
      username: '{{ sso_console_admin_username }}'
      password: '{{ sso_console_admin_password }}'
    validate_certs: false
  no_log: "{{ _no_log }}"
  register: sso_token_result

- set_fact:
    sso_token: '{{ sso_token_result.json.access_token }}'
  no_log: "{{ _no_log }}"
