---
- hosts: automationcontroller
  gather_facts: yes
  vars_files: vars/collection_global_vars.yml
  roles:
    - role: ansible.automation_platform_installer.check_config_static
    - role: ansible.automation_platform_installer.config_dynamic
  tasks:
    - name: Mark controller hosts for rekey
      group_by:
        key: "aap_controller_rekey_hosts"
      changed_when: false
      when:
        - inventory_hostname in groups['automationcontroller'] | default([])
        - rekey_controller | bool or rekey_all | bool

- hosts: aap_controller_rekey_hosts
  gather_facts: yes
  vars_files: vars/collection_global_vars.yml
  tasks:
    - name: Stop Tower services on all nodes
      command: automation-controller-service stop
    - include_role:
        name: ansible.automation_platform_installer.postgres
        tasks_from: vars.yml
    - include_role:
        name: ansible.automation_platform_installer.config_dynamic
    - name: Start database services on primary node if needed
      service:
        name: '{{ postgres_init_name }}'
        state: started
      when: config_dynamic_database == 'internal' and inventory_hostname == groups['automationcontroller'][0]

- hosts: aap_controller_rekey_hosts
  gather_facts: false
  vars_files: vars/collection_global_vars.yml
  tasks:

    - name: Assign primary instance for the rekey command
      set_fact:
        _primary: "{{ groups['automationcontroller'][0] }}"

    - name: generate a new SECRET_KEY
      command: "awx-manage regenerate_secret_key {{ secret_key_override | default('') | ternary('--use-custom-key', '') }}"
      environment:
        TOWER_SECRET_KEY: "{{ secret_key_override | default('') }}"
      register: new_key
      become_user: awx
      no_log: "{{ _no_log }}"
      delegate_to: "{{ _primary }}"
      run_once: True

    - name: distribute the new SECRET_KEY to all nodes
      copy:
        dest: /etc/tower/SECRET_KEY
        content: "{{ new_key.stdout }}"
        mode: '0640'
        backup: yes

    - name: Start Tower services on all nodes
      command: automation-controller-service start
