---
# Note: blocks (for "rescue") do not work in handler included files
- name: Restart pulpcore service
  systemd:
    daemon_reload: true
    name: "pulpcore.service"
    state: restarted
  become: true
  ignore_errors: true
  register: result_restart_pulpcore

- name: Restart pulpcore service (retry)
  systemd:
    daemon_reload: true
    name: "pulpcore.service"
    state: restarted
  become: true
  retries: 5
  delay: 12
  register: result_restarts_pulpcore
  until: result_restarts_pulpcore is succeeded
  when:
    - result_restart_pulpcore is failed

- name: Print status of pulpcore services and fail
  include_tasks: tasks/print_status_and_fail.yml
  when:
    - result_restart_pulpcore is failed
    - result_restart_pulpcore is not defined

- name: Delete symlink from old artifact directory location
  file:
    path: '{{ __pulp_old_artifact_dir }}'
    state: absent
  become: true
