- block:
    - name: Add ee-29 to the EE configuration
      ansible.builtin.set_fact:
        global_job_execution_environments: '{{ global_job_execution_environments | union([ee_29]) }}'
      when: _ee_29_enabled | bool

    - name: Create execution environment list for Hub
      set_fact:
        hub_execution_environments: "{{ hub_execution_environments | default([]) + [{'name': 'Automation Hub ' + item['name'], 'image': item['image'].replace(_ee_image_base, _hub_image_base)}] }}"
      with_items: "{{ global_job_execution_environments }}"

    - name: Update global_job_execution_environments for Hub (non-bundle)
      set_fact:
        _global_job_execution_environments: "{{ global_job_execution_environments + hub_execution_environments }}"
      when:
        - not bundle_install | bool
        - not _ee_from_hub_only | bool

    - name: Update execution environment images for Hub (bundle)
      set_fact:
        _global_job_execution_environments: "{{ hub_execution_environments + global_job_execution_environments }}"
        _control_plane_execution_environment: "{{ control_plane_execution_environment.replace(_ee_image_base, _hub_image_base) }}"
        _container_groups_image: "{{ container_groups_image.replace(_ee_image_base, _hub_image_base) }}"
      when:
        - bundle_install | bool
        - not _ee_from_hub_only | bool

    - name: Update execution environment images for Hub registry only
      set_fact:
        _global_job_execution_environments: "{{ hub_execution_environments }}"
        _control_plane_execution_environment: "{{ control_plane_execution_environment.replace(_ee_image_base, _hub_image_base) }}"
        _container_groups_image: "{{ container_groups_image.replace(_ee_image_base, _hub_image_base) }}"
      when: _ee_from_hub_only | bool

  run_once: true
  when: groups['automationhub'] | default([]) | length

- name: Set Execution Environment configuration
  template:
    dest: /etc/tower/conf.d/execution_environments.py
    force: yes
    src: execution_environments.py.j2
    mode: '0640'
    owner: root
    group: awx
  notify:
    - restart nginx
    - restart supervisor

- name: Set default image for Container Groups
  template:
    dest: /etc/tower/conf.d/container_groups.py
    force: yes
    src: container_groups.py.j2
    mode: '0640'
    owner: root
    group: awx
  notify:
    - restart nginx
    - restart supervisor
