- name: Enable sc
  lineinfile:
    path: /etc/profile
    line: "source scl_source enable rh-postgresql96"

- name: Init db
  shell: "source scl_source enable rh-postgresql96 && /opt/rh/rh-postgresql96/root/usr/bin/postgresql-setup initdb"
  become: yes
  become_user: root

- name: Create postgres user environment
  shell: "source scl_source enable rh-postgresql96 && /usr/bin/scl enable rh-postgresql96 -- psql"
  become: yes
  become_user: "{{ pg_user }}"

- name: Generate postgresql.conf
  template:
    src: single_postgresql.conf.j2
    dest: "{{ pg_path }}/data/postgresql.conf"
    owner: "{{ pg_user }}"
    group: "{{ pg_group }}"
    mode: 0600

- name: Generate pg_hba.conf
  template:
    src: single_pg_hba.conf.j2
    dest: "{{ pg_path }}/data/pg_hba.conf"
    owner: "{{ pg_user }}"
    group: "{{ pg_group }}"
    mode: 0600

- name: Create archive folder
  file:
    path: "{{ pg_path }}/archive/"
    state: directory
    owner: "{{ pg_user }}"
    group: "{{ pg_group }}"
    mode: 0700

- name: Restart server on master
  service:
    name: rh-postgresql96-postgresql
    state: restarted
  become: yes
  become_user: root
